# .github/workflows/node.js.yaml

# This workflow will do a clean install of node dependencies, build the source
# code and run tests across different versions of node on ubuntu, macos and
# windows.
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    strategy:
      matrix:
        include:
          # See https://nodejs.org/en/about/releases/.

          # Run all current/lts node versions on ubuntu.
          - runs-on: ubuntu-latest
            node-version: 14.x # Until EOL 2023-04-30

          - runs-on: ubuntu-latest
            node-version: 16.x # Until EOL 2024-04-30

          - runs-on: ubuntu-latest
            node-version: 18.x # Until EOL 2025-04-30

          # Just run LTS node versions on Windows and MacOS
          - runs-on: windows-latest
            node-version: 16.x # Until Maint 2022-10-18

          - runs-on: macos-latest
            node-version: 16.x # Until Maint 2022-10-18

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.runs-on }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: npm run ci:build
